commands: Remove unused code after 1d3681f52135
Clang 13 reports:

../sway/commands.c:470:23: error: variable 'context' set but not used
[-Werror,-Wunused-but-set-variable]
        enum command_context context = 0;
                             ^
Last use of was removed in commit 1d3681f52135.

Downstream PR: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=258813